// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaeaCFXvM6xh2qR8GKii7lIbVVXOeOUQY',
    appId: '1:736373946179:web:1c282b59987675229161f6',
    messagingSenderId: '736373946179',
    projectId: 'ai-powered-mental-health-compa',
    authDomain: 'ai-powered-mental-health-compa.firebaseapp.com',
    storageBucket: 'ai-powered-mental-health-compa.firebasestorage.app',
    measurementId: 'G-10GK42JK0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2RPoy9kJIc1nRyBcwP8GAmQAZVJtmggE',
    appId: '1:736373946179:android:1c4cf4a027f3d53f9161f6',
    messagingSenderId: '736373946179',
    projectId: 'ai-powered-mental-health-compa',
    storageBucket: 'ai-powered-mental-health-compa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALRhczhOhdab2ZYyi4sa3xqKX3GAScxHs',
    appId: '1:736373946179:ios:b172ba90e6ce34c19161f6',
    messagingSenderId: '736373946179',
    projectId: 'ai-powered-mental-health-compa',
    storageBucket: 'ai-powered-mental-health-compa.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALRhczhOhdab2ZYyi4sa3xqKX3GAScxHs',
    appId: '1:736373946179:ios:b172ba90e6ce34c19161f6',
    messagingSenderId: '736373946179',
    projectId: 'ai-powered-mental-health-compa',
    storageBucket: 'ai-powered-mental-health-compa.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaeaCFXvM6xh2qR8GKii7lIbVVXOeOUQY',
    appId: '1:736373946179:web:9ff18c3522ab7ea09161f6',
    messagingSenderId: '736373946179',
    projectId: 'ai-powered-mental-health-compa',
    authDomain: 'ai-powered-mental-health-compa.firebaseapp.com',
    storageBucket: 'ai-powered-mental-health-compa.firebasestorage.app',
    measurementId: 'G-L9K0HWZ957',
  );
}
